name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o=.github/workflows/kenv.linux.amd64 ./main/
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - run: npx semantic-release
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: metro-digital-bot
          GIT_AUTHOR_EMAIL: info@metro.digital
          GIT_COMMITTER_NAME: metro-digital-bot
          GIT_COMMITTER_EMAIL: info@metro.digital
