name: Test
on:
  pull_request:
    types: [opened, synchronize]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: |
          go mod tidy
          ~/go/bin/ginkgo -tags unitTests -randomizeAllSpecs -failFast -r .
      - run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.39.0
      - run: bin/golangci-lint run -c .golangci.yml ./...